title: EEB-5449
author: University of Connecticut
email: evolution@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
 Course web site for Fall semester 2026
baseurl: "/"
#baseurl: "/evolution"
#url: "http://uconneeb.github.io"
markdown: kramdown
theme: minima
exclude: [
        'image-links.md',
    ]
header_pages:
  - schedule.md
  - grading.md
  - contact.md
plugins:
  - jekyll-seo-tag